//
//  YearGenerator.swift
//  Pagination Tutorial
//
//  Created by Ge Huang on 2022/1/9.
//

import Foundation
// Error handling not used becaused data is generated by ourself
enum dateGenerateError: Error {
    case invalidUrl
    case errorDecode
    case failed(error: Error)
    case unknownError
}

struct DateManager {
    static let shared = DateManager()
    
    func getDate(perPage: Int = 30, sinceDate: Int) -> [Date] {
        // 2
        var Result:[Date] = []
        for i in sinceDate..<(sinceDate + perPage) {
            Result.append(Date(year: i))
        }
        return Result
    }
}
